const SIGNUP           = 'SIGNUP';
const SIGNUP_SUCCESS   = 'SIGNUP_SUCCESS';
const SIGNUP_FAIL      = 'SIGNUP_FAIL';
const LOGIN            = 'LOGIN';
const LOGIN_SUCCESS    = 'LOGIN_SUCCESS';
const LOGIN_FAIL       = 'LOGIN_FAIL';
const KEY_PAIR_CREATED = 'KEY_PAIR_CREATED';
const TOKEN_CREATED    = 'TOKEN_CREATED';
const RESET_ERROR      = 'RESET_ERROR';

export {
    SIGNUP,
    SIGNUP_SUCCESS,
    SIGNUP_FAIL,
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    KEY_PAIR_CREATED,
    TOKEN_CREATED,
    RESET_ERROR
};
